package com.example.demo.common;

public enum ApiErrorKey {
    REGISTRATION_VALIDATION,
    USER_PROFILE_VALIDATION,
    INVALID_JSON,
    USERNAME_ALREADY_EXISTS,
    NICKNAME_ALREADY_EXISTS,
    REGISTRATION_CONFLICT,
    USER_PROFILE_CONFLICT,
    INVALID_CREDENTIALS,
    INVALID_REFRESH_TOKEN,
    UNAUTHORIZED
}
